In [12]:
import numpy as np
import pandas as pd
import matplotlib.pylab as plt

data_=pd.read_csv('./after.csv')
feature=np.array(data_.iloc[:,1:-1])  # 将参数与特征进行分离，返回数据类型为数组
labels = data_['label'].tolist()   # 将'label'标签提取出来转换为列表类型,方便后续使用

from sklearn import neighbors
from sklearn.model_selection import train_test_split
feautre_train,feautre_test,label_train,label_test=train_test_split(feature,labels,test_size=0.2)
# 指出训练集的标签和特征以及测试集的标签和特征，0.2为参数，对测试集以及训练集按照2:8进行划分
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()

model.fit(feautre_train,label_train) # 现在只需要传入训练集的数据
prediction=model.predict(feautre_test)
#print(prediction)

labels=['good','bad']
classes=['good',
         'bad']
from sklearn.metrics import classification_report

result_=classification_report(label_test,prediction,target_names = classes)
# target_names：类别；digits：int，输出浮点值的位数
print(result_)



              precision    recall  f1-score   support

        good       0.85      0.99      0.92     69068
         bad       0.80      0.22      0.34     15025

    accuracy                           0.85     84093
   macro avg       0.83      0.60      0.63     84093
weighted avg       0.84      0.85      0.81     84093



In [11]:
import numpy as np
import pandas as pd
import matplotlib.pylab as plt

data_=pd.read_csv('./after.csv')
feature=np.array(data_.iloc[:,1:-1])  # 将参数与特征进行分离，返回数据类型为数组
print(feature)
labels = data_['label'].tolist()   # 将'label'标签提取出来转换为列表类型,方便后续使用


from sklearn.model_selection import train_test_split
feautre_train,feautre_test,label_train,label_test=train_test_split(feature,labels,test_size=0.2)
# 指出训练集的标签和特征以及测试集的标签和特征，0.2为参数，对测试集以及训练集按照2:8进行划分
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=100, max_depth=3,random_state=0)

model.fit(feautre_train,label_train) # 现在只需要传入训练集的数据
prediction=model.predict(feautre_test)
#print(prediction)

labels=['good','bad']
classes=['good',
         'bad']
from sklearn.metrics import classification_report

result_=classification_report(label_test,prediction,target_names = classes)
# target_names：类别；digits：int，输出浮点值的位数
print(result_)

[[  0   0  74 ...   0   0   0]
 [  0   0  37 ...   0   0   0]
 [  0   0  65 ...   0   0   0]
 ...
 [  0   0  49 ...   0   0   0]
 [  0   0  17 ...   0   0   0]
 [  0   0 176 ...   0   0   0]]
              precision    recall  f1-score   support

        good       0.84      1.00      0.91     69069
         bad       0.94      0.12      0.21     15024

    accuracy                           0.84     84093
   macro avg       0.89      0.56      0.56     84093
weighted avg       0.86      0.84      0.79     84093

